### PR TITLE
Update to work with firefox 44.0

### PR DESCRIPTION
**Pull request by InternalError503**
In firefox 44.0 about:addons-memory no longer works, The update and changes below resolve this in 44.0

### CODE REVIEW

**Comment by InternalError503** [comment]
This should resolve the issues reported [here](https://github.com/nmaier/about-addons-memory/issues/21)

**Comment by Noitidart** [comment]
Thanks so much for this @InternalError503 , this addon is extremely useful for me as an addon dev.

**Comment by saji89** [comment]
@InternalError503 Thanks man. Wondering if @nmaier has abandoned this project. Lot of comments on the addons website worrying about this: https://addons.mozilla.org/en-US/firefox/addon/about-addons-memory/?src=userprofile
It also shows: "Last Updated: October 24, 2014".

**Comment by InternalError503** [comment]
@saji89 
It certainly appears that way, Same with download them all which is a shame as its another amazing addon.

**Comment by sammcj** [comment]
Thanks for reporting this bug dude/dudette, I was wondering why it stopped working, looks to be unmaintained as you've said above, how do we get Firefox / Mozilla to shift ownership or did you want to fork it and call it like v2 or something (heh).

cc/ @nmaier

**Comment by sammcj** [comment]
I just did a build of the working fork - BUT ITS COMPLETELY UNSIGNED, YMMV etc, etc, etc, but it works for me.

[about-addons-memory.xpi.zip](https://github.com/nmaier/about-addons-memory/files/394284/about-addons-memory.xpi.zip)

**Comment by InternalError503** [comment]
@sammcj 

You can get the latest build [here](https://github.com/nmaier/about-addons-memory/issues/21#issuecomment-222915486) works with Firefox 24.0 and up.

You can also get it directly from my [local repo](https://github.com/InternalError503/about-addons-memory)

I originally was going to post to AMO but someone else did [here](https://github.com/nmaier/about-addons-memory/issues/21#issuecomment-206526673) the only issue is they appeared to have abandoned that idea also, So now i am not sure if to push it to AMO myself, It's a great addon that i want to see working for as long as possible before been wiped out with web extensions.

**Comment by sammcj** [comment]
Oh thank you!

Yes I'm not sure how I feel about web extensions.

The fact that they're all in JavaScript scares me - JS is one of the problems on the internet - not one of the solutions.

**Comment by nmaier** [comment]
This add-on certainly was not a priority. But removing the `LICENSE` file in a commit? Certainly not.

I merged in the https://github.com/nmaier/extsdk and made two changes and it seems to work again. @InternalError503 if you got bugfixes or improvements, please do a separate PR for that. Depending on how that goes, you becoming a collab and/or AMO owner is a possibility (provided you stop trying to remove the license again)

**Comment by InternalError503** [comment]
@nmaier Thanks for letting me know, I accidentally deleted it along with a few other files i was working on, Real time reporting and it was almost done :( , This was not intentional at all, Please forgive its a honest mistake, If your going to update it then that is epic news, Glad to have you back.

Out of the above commits which ones would you like me to make separate PR's for :+1:  and i will get them done as soon as i can.

**Comment by nmaier** [comment]
@InternalError503 I never assume malice on the first time 😀

**Comment by GuardianMajor** [comment]
@InternalError503 and @nmaier I know this has been a very long time ago and forgive me for bumping it but I was wondering if there was a more recent working version of this addon as none of the ones that appear anywhere on the repo by anyone works anymore. I am on 56 at the moment and can really use what this addon does and would appreciate it. Thank you in advance.

**Pull request closed without merging**
